version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: containers
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tinsmart
      MYSQL_USER: aldair
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3308:3306"  # Cambiado el puerto del host a 3308
